const test = require('node:test')
const assert = require('node:assert/strict')
const Module = require('node:module')
const load = Module._load
Module._load = function (name, parent, main) {
  if (name === '@mueo/koishi-plugin-cocofaith-core') return require('../../koishi-plugin-cocofaith-core/lib/index.js')
  return load.call(this, name, parent, main)
}
const { App } = require('koishi')
const core = require('../../koishi-plugin-cocofaith-core/lib/index.js')
const business = require('../lib/index.js')

test('collection persists acquisitions, ignores rollbacks, separates limited pools and awards bonuses once', async () => {
  const app = new App()
  app.plugin(require('@minatojs/driver-sqlite').default, { path: ':memory:' })
  app.plugin(core, { gameDay: { enabled: false } })
  app.plugin(business, {})
  await app.start()
  try {
    const user = await app.faithCore.faiths.registerUser({ adapter: 'onebot', type: 'qq_account', value: 'collection-test', scope: 'global' }, app.faithCore.faiths.all()[0].name, 1000)
    const api = app.faithBusiness.interfaces.use('probe', 'collection', 'default', new Set(['collection']))
    const title = app.faithBusiness.interfaces.use('probe', 'title', 'default', new Set(['title']))
    const scope = app.faithCore.createBusinessScope('collection_probe')
    assert.deepEqual(await scope.users.listUids(0, 1), [user.uid])
    assert.deepEqual(await scope.users.listUids(user.uid, 1), [])
    await assert.rejects(scope.users.listUids(0, 501))
    const catalog = new business.CollectionCatalog(scope.items)
    const limitedEggs = [...catalog.snapshot().values()].filter((e) => e.item.level === 'URE')
    assert.deepEqual(limitedEggs.map((e) => e.item.name).sort(), ['欢笑假面2025.9.1', '永不散场的嘉年华入场券'].sort())
    assert.ok(limitedEggs.every((e) => e.category === '彩蛋' && e.pool === '限定彩蛋'))
    const normal = [...catalog.snapshot().values()].filter((e) => !e.pool && e.item.level === 'SP')
    assert.ok(normal.length)
    const first = normal[0].item.item_id
    await assert.rejects(scope.transaction.run(user.uid, async (tx) => {
      await tx.items.give(first, 1)
      throw new Error('rollback')
    }))
    assert.equal(await api.has(user.uid, first), false)
    await scope.transaction.run(user.uid, async (tx) => {
      for (const entry of normal) await tx.items.give(entry.item.item_id, 1)
    })
    assert.equal(await api.has(user.uid, first), true)
    assert.ok((await title.listOwned(user.uid)).some((t) => t.id === 'void-collector'))
    await scope.transaction.run(user.uid, async (tx) => { await tx.items.take(first, 1) })
    assert.equal(await api.has(user.uid, first), true)
    await api.refresh(user.uid)
    await api.refresh(user.uid)
    const bonus = await scope.bonuses.calculate({ uid: user.uid, type: 'void_prayer.daily_limit', baseValue: 10 })
    assert.equal(bonus.finalValue, 20)
    const complete = [...catalog.snapshot().values()].filter((e) => !e.pool && (e.item.level === 'SSS' || e.category === '彩蛋'))
    await scope.transaction.run(user.uid, async (tx) => {
      for (const entry of complete) await tx.items.give(entry.item.item_id, 1)
    })
    const ownedTitles = (await title.listOwned(user.uid)).map((t) => t.id)
    assert.ok(ownedTitles.includes('great-collector'))
    assert.ok(ownedTitles.includes('easter-egg-collector'))
    assert.equal((await scope.bonuses.calculate({ uid: user.uid, type: 'void_prayer.daily_limit', baseValue: 10 })).finalValue, 30)
    await Promise.all([api.refresh(user.uid), api.refresh(user.uid)])
    const rows = await app.database.get('faith_business_collection', { uid: user.uid })
    assert.equal(rows.length, 1)
    assert.equal(new Set(rows[0].items).size, rows[0].items.length)
    const item = { item_id: 'collection_dynamic', name: '动态收藏测试', type: '道具', level: 'SSS', description: '', max_quantity: 0, marketable: false, price: 0, obtainable: false }
    scope.items.register(item)
    assert.ok(catalog.snapshot().has(item.item_id))
    const dispose = api.configure(item.item_id, { pool: '测试限定' })
    assert.throws(() => api.configure(item.item_id, { excluded: true }))
    await scope.transaction.run(user.uid, async (tx) => { await tx.items.give(item.item_id, 1) })
    assert.ok((await api.details(user.uid, true)).entries.some((e) => e.item.item_id === item.item_id && e.collected))
    dispose()
    const exclude = api.configure(item.name, { excluded: true })
    assert.equal((await api.progress(user.uid)).some((r) => r.pool === '测试限定'), false)
    assert.equal(await api.has(user.uid, item.item_id), true)
    exclude()
    assert.ok((await api.progress(user.uid)).every((r) => r.collected <= r.total))
    await assert.rejects(api.details(user.uid, false, -1))
    const result = await app.faithBusiness.dispatch({ uid: user.uid, scene: 'group', content: '/图鉴 详情' })
    assert.equal(result.result.type, 'text')
    assert.ok(result.result.content.split('\n').length <= 13)
    const denied = await app.faithBusiness.dispatch({ uid: user.uid, scene: 'group', content: '信仰管理 图鉴 刷新' })
    assert.equal(denied.result.type, 'silent')
    app.faithCore.permissions.register('faith.creator', () => true)
    const refreshed = await app.faithBusiness.dispatch({ uid: user.uid, scene: 'group', content: '信仰管理 图鉴 刷新' })
    assert.match(refreshed.result.content, /检查 1 人/)
    await app.faithBusiness.disable('collection')
    await app.faithBusiness.enable('collection')
    const reopened = app.faithBusiness.interfaces.use('probe', 'collection', 'default', new Set(['collection']))
    assert.equal(await reopened.has(user.uid, first), true)
    await scope.lifecycle.dispose()
  } finally { await app.stop() }
})
